version: 'version'
services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./google_credentials.json:/app/google_credentials.json:ro
      - ./resources:/app/resources:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
